DewGew/Domoticz-Google-Assistant

default_config.py
smarthome.py
states.py
trait.py

No need to enter SecPassword for securitypanel in config.py anymore

Removed SecPassword

---

default_config.py
smarthome.py
trait.py

Automaticly fetch temp unit ( C or F)

Fetch Temp Unit

---

smarthome.py
sync.py

Added device type 'Temp + Humidity + Baro' as device in type tempDOMAIN

Update smarthome.py and sync.py

---

default_config.py
helpers.py
smarthome.py
trait.py

This example is for locking the door:
"The front door lock has low battery. Locking the front door."

Report low batteries

---

auth.py

Do double unquoting of parameters

Fixes double quoting of parameters. Fix #23

---

trait.py

In my case; For some reason "Color" is emtpy, which caused an JSONDecodeError  (ConBee RGBW Bulbs)

Resolved an unknownError when using a Colro Switch

---

smarthome.py
trait.py

Get rid of "There was an error controlling security device" message

ArmDisarmTrait Rewrite

---

const.py
trait.py

Add possibility to change color temperatuer
#44

Add colortemperture

---

trait.py

Recalculate kelvin to percent

---

const.py
smarthome.py
trait.py

Next small pull request, now fans are shown as fans instead of lightbulb.

Added discovery Fan devices

---

README.md
const.py
default_config

Very small fix which corrects what seems to be a typo.

Fixed ClientSectret => ClientSecret

---

const.py
login.html
trait.py

Conversion Fahrenheit Celsius

---

const.py
default_config
helpers.py
login.html
smarthome.py

Add custom path to logfile #73

Configurable logfile path

---

.github/ISSUE_TEMPLATE/stale.yml
.travis.tml
README.md
const.py
helpers.py
login.html
trait.py

- Visual changes
- Tempconvert for Thermostat (fahrenheit)
- Fixes issue open default_config at first run

New release

---

smarthome.py

Added async_update to query

---

README.md
const.py
helpers.py
login.html
smarthome.py

Rewrite update
Add ssl info in UI
Add ssl info in README.md

Rewrite update

---

const.py
login.html
smarthome.py

- Added support for color switch push button
- Docker support

Merge beta into master

---

Dockerfile

When automating builds via dockerhub we need beta dockerfile to pull beta branch

Make beta branch dockerfile build from beta branch

---

const.py
login.html
smarthome.py
trait.py

Add stop function for blinds during movement

Stop blinds

---

const.py
login.html
smarthome.py
trait.py

Fixes blinds percentage issues

Blinds fix

---

const.py
login.html
smarthome.py
trait.py

Reverts DewGew/Domoticz-Google-Assistant#138

Revert "Blinds fix"

---

const.py
trait.py

Added function to query battery level

Battery level

---

const.py
trait.py

Fix 2FA issue with Pin code

---

README.md
const.py
helpers.py
smarthome.py

- Rewrite Report State handling
- Fix issue with stream camera to chromecast
- Added "White" to Color Switch

Merge Beta to Master

---

const.py
smarthome.py

Fix if dzversion and dzVents const missing if not connected to domoticz.
#155

Fix if dzversion and dzVents const missing

---

config/default_config
const.py
smarthome.py
trait.py

- Added debug log when voicecontrol tag is found
- Get roomname  from domoticz plans
- Remove image override
- Added 'Already in state' error in openclose trait
- Fix devicetype issues
- Added switch and blinds to devicetype function
- Remove dzVents version check, not needed anymore

Merge Beta

---

const.py
smarthome.py

Fix Door lock inverted issue #189

Merge beta in arm32

---

const.py
helpers.py

Get dzga uptime instead of system uptime

Rewrite uptime

---

auth.py
const.py
smarthome.py

Added  logging failed login IP

---

const.py
smarthome.py

Suggestion from @vreesie18  in issue #223 
Function to change primary name in config:
```
<voicecontrol>
name = My cool name
<voicecontrol>
```
or
```
Device_Config:
123:
name: 'My cool name'
```

Change primary name

---

const.py
helpers.py
smarthome.py
templates/base.html
templates/help.html
templates/home.html
templates/js/functions.js
templates/js/sidebar.js
templates/logs.html
templates/settings.html
templates/sidebar.html

UI Settings page

---

requirements/pip-requirements.txt
smarthome.py

New features Notification on specific chomecast device with specific volume :
"/say?bonjour/fr@60@Kitchen%20speaker" or "/play?doorbell1.mp3@40@Living%20room%20TV" (@Volume level@target device).
After the message the media and volume that was playing will be restored.
An extra library of functions is available "/pycast?" will give access to new functions : status, devices, switchdevice, volume, setvolume, pause, play, stop, playmedia
(see attached files for examples)
Basically there are now structured json responses that can be used with the dzvents http events.
See attached files :  https://github.com/DewGew/Domoticz-Google-Assistant/issues/239#issuecomment-830144555
! pip install -r requirements/pip-requirements.txt before testing beta.

New features chromecast notifications 

---

smarthome.py

Improvement on IP Port determination from config file and extension on debug possibilities when sending sound file to Chromecast.

IP_Port from Config and debug extension

---

smarthome.py

adding blinds with stop as percentage blinds

---

Dockerfile
smarthome.py

post sync fix

---

const.py
smarthome.py

Changes in Domoticz latest beta #348

Add Setpoint to Thermostats
